In [2]:
import numpy as np

In [4]:
a = np.matrix('1 2; 3 4')
b = np.matrix('5 6; 7 8')

np.dot(a,b)

matrix([[19, 22],
        [43, 50]])

In [6]:
m = np.matrix('1 2;3 4')
#m.transpose()
m.T

matrix([[1, 3],
        [2, 4]])

In [7]:
a.trace()

matrix([[5]])

In [13]:
np.linalg.matrix_rank(a)

2

In [15]:
np.linalg.det(a)

-2.0000000000000004

In [17]:
np.linalg.inv(a)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [21]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=matrix([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))